---
language: python

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# https://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  apt:
    packages:
      - ant

# https://docs.travis-ci.com/user/caching/
cache: pip

env:
  - SPHINXOPTS="-W"

script:
  - make clean html
  - tar -zcvf omero-documentation.tar.gz -C omero/_build/html/ ./
  - tar -zcvf contributing.tar.gz -C contributing/_build/html/ ./

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - omero-documentation.tar.gz
    - contributing.tar.gz
  skip_cleanup: true
  on:
    tags: true
